/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JRadicom */

#ifndef _Included_JRadicom
#define _Included_JRadicom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JRadicom
 * Method:    q_read
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_JRadicom_q_1read
  (JNIEnv *, jobject);

/*
 * Class:     JRadicom
 * Method:    q_memread
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_JRadicom_q_1memread
  (JNIEnv *, jobject);

/*
 * Class:     JRadicom
 * Method:    q_setdt
 * Signature: (IIIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_JRadicom_q_1setdt
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     JRadicom
 * Method:    q_calibrate
 * Signature: (IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_JRadicom_q_1calibrate
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     JRadicom
 * Method:    read_header
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_JRadicom_read_1header
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     JRadicom
 * Method:    process_read
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_JRadicom_process_1read
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     JRadicom
 * Method:    print
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JRadicom_print
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
