/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jradicom_JRadicom */

#ifndef _Included_jradicom_JRadicom
#define _Included_jradicom_JRadicom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jradicom_JRadicom
 * Method:    q_read
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jradicom_JRadicom_q_1read
  (JNIEnv *, jobject);

/*
 * Class:     jradicom_JRadicom
 * Method:    q_memread
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jradicom_JRadicom_q_1memread
  (JNIEnv *, jobject);

/*
 * Class:     jradicom_JRadicom
 * Method:    q_setdt
 * Signature: (IIIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_jradicom_JRadicom_q_1setdt
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jradicom_JRadicom
 * Method:    q_calibrate
 * Signature: (IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_jradicom_JRadicom_q_1calibrate
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jradicom_JRadicom
 * Method:    r_read
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jradicom_JRadicom_r_1read
  (JNIEnv *, jobject);

/*
 * Class:     jradicom_JRadicom
 * Method:    read_header
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_jradicom_JRadicom_read_1header
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     jradicom_JRadicom
 * Method:    process_read
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_jradicom_JRadicom_process_1read
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
